"""Initial schema

Revision ID: 30fd2a308bbb
Revises: 
Create Date: 2026-09-12 11:47:12.218193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30fd2a308bbb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('projects_log')
    op.alter_column('saved_projects', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('saved_projects', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('saved_projects', 'project_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('saved_projects', 'timestamp',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('saved_projects', 'plot_length',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('saved_projects', 'plot_width',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.drop_constraint(None, 'saved_projects', type_='foreignkey')
    op.add_column('users', sa.Column('failed_attempts', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('lockout_until', sa.DateTime(), nullable=True))
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('users', 'username',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password_hash',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_column('users', 'lockout_until')
    op.drop_column('users', 'failed_attempts')
    op.create_foreign_key(None, 'saved_projects', 'users', ['user_id'], ['id'])
    op.alter_column('saved_projects', 'plot_width',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('saved_projects', 'plot_length',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('saved_projects', 'timestamp',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('saved_projects', 'project_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('saved_projects', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('saved_projects', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.create_table('projects_log',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('timestamp', sa.TEXT(), nullable=True),
    sa.Column('area', sa.REAL(), nullable=True),
    sa.Column('floors', sa.INTEGER(), nullable=True),
    sa.Column('tier', sa.TEXT(), nullable=True),
    sa.Column('grade', sa.TEXT(), nullable=True),
    sa.Column('estimated_cost', sa.REAL(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
